"
Please comment me using the following template inspired by Class Responsibility Collaborator (CRC) design:

For the Class part:  State a one line summary. For example, ""I represent a paragraph of text"".

For the Responsibility part: Three sentences about my main responsibilities - what I do, what I know.

For the Collaborators Part: State my main collaborators and one line about how I interact with them. 

Public API and Key Messages

- message one   
- message two 
- (for bonus points) how to create instances.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.


    Implementation Points
"
Class {
	#name : #Card,
	#superclass : #Object,
	#category : #'IngSoft2-Model'
}

{ #category : #'as yet unclassified' }
Card >> cardClassesWithNoTarget [
	| cardClasses |
	cardClasses := OrderedCollection new.
	cardClasses add: AccelerationCard.
	cardClasses add: RepeatCard.
	^ cardClasses 
]

{ #category : #'as yet unclassified' }
Card >> cardsAffectingPlayers [
	| cardClasses |
	cardClasses := OrderedCollection new.
	cardClasses add: SpeedCard.
	cardClasses add: OverloadCard.
	^ cardClasses
]
